### PR TITLE
Adds julia api + docker compose

### PR DESCRIPTION
**Pull request by fysp11**
This is the most annoying one. The task was to bring both julia and app implementations to a monorepo and implement a docker compose. It is what is :p

### CODE REVIEW

**Comment by evanp** [comment]
OK, here's my review, based on trying to get this built.

1. We need a README.md with instructions on how to use the docker-compose file.
2. There's an environment variable that needs to be set before running docker-compose, `CO2_PRICING_DATABASE_URL`. I assume this is postgresql, and that it's in the form "postgres://user:password@host/database"
3. When I run `docker build`, I get an error: 

```
> [co2-pricing-app builder 5/5] RUN yarn build && yarn install --production --ignore-scripts --prefer-offline:
#0 0.637 yarn run v1.22.19
#0 0.680 $ next build
#0 1.274 ❌ Invalid environment variables:
#0 1.274  NEXT_PUBLIC_MIMIFUND_API_URL: Required
#0 1.274 
#0 1.274 error - Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
#0 1.290 
#0 1.290 > Build error occurred
#0 1.291 Error: Invalid environment variables
#0 1.291     at file:///app/src/env/client.mjs:22:9
#0 1.291     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
#0 1.291     at async Promise.all (index 0)
#0 1.291     at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
#0 1.291     at async file:///app/next.config.mjs:6:38
#0 1.320 error Command failed with exit code 1.
#0 1.320 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by evanp** [comment]
I tried setting the env var in my shell before running docker-compose build, and I tried adding it to the `app` section of the docker compose file. Neither worked. 

There's an `app/.env.example` file, but it doesn't include this variable.

**Comment by fysp11** [comment]
Will rebase with the new features from `main` branch and make it reproduceable again.

**Comment by fysp11** [comment]
@evanp I made the changes, the README should be enough to reproduce the application (docs on this branch's root folder)

**Comment by evanp** [comment]
Thanks for the hard work! I was able to build the repo and run it on my workstation.

The one thing I'd recommend is specifying the best URL for checking the app is running. It's at `http://localhost:3000/`, but that's not in the README.

**Review by evanp — APPROVED** [review]
I was able to build and run the app. Nice job!

**Pull request merged**
